spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8
      username: root
      password: 12345678
      initial-size: 1
      min-idle: 1
      max-active: 20

mybatis:
  type-aliases-package: com.lil.fmmall.entity
  mapper-locations: classpath:mappers/*Mapper.xml

